---
engines:
  csslint:
    enabled: false
  phpcodesniffer:
    enabled: false  
  duplication:
    enabled: false
    config:
      languages:
      - php:
          mass_threshold: 36
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
#      rulesets: "unusedcode,codesize,naming,ruleset.xml"
ratings:
  paths:
  - "**.php"
exclude_paths:
- vendor/
- public/
- .idea/
- .phan/
- .vagrant/
- _ide_helper.php 


- database

# Providers has default laravel naming convention so that ignored from test
- app/Providers
- app/Services
# modules package not done to test
- app/Modules
